services:

  ####################################################################################################
  # PHP
  ####################################################################################################
  app:
    build: .docker/php
    container_name: laravel-starter
    ports:
      - 9001:9001
    volumes:
      - .:/var/www:cached
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - .:/var/www
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge